BEGIN TRANSACTION;


CREATE TABLE ACCOUNTS (
	ACCOUNT_ID INTEGER PRIMARY KEY,
	ACCOUNT_NUMBER TEXT,
	ACCOUNT_DESCRIPTION TEXT,
);


CREATE TABLE ACCOUNT_TRANSACTIONS (
	TRANSACTION_ID INTEGER PRIMARY KEY,
       	ACCOUNT_ID INTEGER,
       	SPOT_RATE REAL,
       	PAYMENTS_RECIEPTS REAL,
       	ACCOUNT_CASH_BALANCE REAL,
       	REALIZED_PROFIT_LOSS REAL,
       	PREMIUMS REAL,
       	COMMISSIONS REAL,
       	FEES REAL,
       	NEW_CASH_BALANCE REAL,
       	OPEN_TRADE_EQUITY REAL,
       	TOTAL_EQUITY REAL,
       	OPTION_MARKET_VALUE REAL,
       	LONG_OPTION_VALUE REAL,
       	SHORT_OPTION_VALUE REAL,
       	NET_LIQUIDATING_VALUE REAL,
       	INITIAL_MARGIN REAL,
       	MAINTENANCE_MARGIN REAL,
       	RISK_MAINTENANCE REAL,
       	RISK_INITIAL REAL,
       	COLLATERAL_USED REAL,
       	MARGIN_DEFAULT_EXCESS REAL
);


CREATE TABLE CONTRACTS (MARKET_ID NUMERIC,
       	EXPIRATION_DATE DATE,
       	CONTRACT_ID INTEGER PRIMARY KEY,
       	CONTRACT_DESCRIPTION TEXT
);

CREATE TABLE LONG_TERM_HOLDINGS (
	CONTRACT_ID NUMERIC,
       	DATE_BOUGHT DATE,
       	QUANTITY NUMERIC,
       	COST NUMERIC,
       	CURRENT_PRICE NUMERIC,
       	CURRENT_DATE DATE,
       	HOLDING_ID INTEGER PRIMARY KEY,
       	CURRENT_VALUE NUMERIC,
       	PROFIT_LOSS NUMERIC
);

CREATE TABLE MARKET_TYPES (
	MARKET_ID INTEGER PRIMARY KEY,
       	MARKET_DESCRIPTION TEXT
);

INSERT INTO MARKET_TYPES VALUES(1,'COMEX');
INSERT INTO MARKET_TYPES VALUES(2,'NYSEL');
INSERT INTO MARKET_TYPES VALUES(3,'CME');
INSERT INTO MARKET_TYPES VALUES(4,'CBOT');


CREATE TABLE CURRENCIES (
	CURRENCY_ID INTEGER PRIMARY KEY,
	CURRENCY_DESCRIPTION TEXT
);

CREATE TABLE POSITION_TYPES (
	POSITION_TYPE_ID INTEGER PRIMARY KEY,
	POSITION_TYPE_DESCRIPTION TEXT
);

INSERT INTO POSITION_TYPES VALUES(NULL, 'SHORT');
INSERT INTO POSITION_TYPES VALUES(NULL, 'LONG');
INSERT INTO POSITION_TYPES VALUES(NULL, 'LONG TERM HOLDING');

CREATE TABLE POSITIONS (
	CURRENCY NUMERIC,
       	DEBIT NUMERIC,
       	CREDIT NUMERIC,
       	ACCOUNT_ID NUMERIC,
       	OPEN NUMERIC,
       	PRICE NUMERIC,
       	CONTRACT_ID NUMERIC,
       	SHORT_QUANTITY NUMERIC,
       	LONG_QUANTITY NUMERIC,
       	MARKET_ID NUMERIC,
       	POSITION_ID INTEGER PRIMARY KEY,
       	DATE DATE
);

-- ********************************************************
--  Logging
-- ********************************************************

CREATE TABLE LOG_EVENT_TYPES (
	EVENT_TYPE_ID INTEGER PRIMARY KEY,
       	EVENT_TYPE_DESCRIPTION TEXT
);

INSERT INTO LOG_EVENT_TYPES VALUES(1,'UPDATE');
INSERT INTO LOG_EVENT_TYPES VALUES(2,'INSERT');
INSERT INTO LOG_EVENT_TYPES VALUES(3,'DELETE');



CREATE TABLE MASTER_LOG (
       	EVENT_ID INTEGER PRIMARY KEY,
       	TIMESTAMP_GMT DATETIME
       	LOG_EVENT_TYPE INTEGER,
	EVENT_INFO TEXT,
);

COMMIT;
